---
title: "md-highway-data"
author: "Ryan E. Little"
date: "11/8/2019"
source: http://maps.roads.maryland.gov/traffictrends/
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries

```{r}
library(tidyverse)  # attaches purrr and readr
library(lubridate)
library(rvest)
library(downloader)
library(R.utils)
library(rlist)
library(here)
library(janitor)
library(scales)
library(ggrepel)
library(ggplot2)
# library(fs)
# library(stringr)

# library(retrosheet)
# install.packages('retrosheet')
# devtools::install_github("rmscriven/retrosheet")

options(scipen=999)
```

```{r}

#clear environment for when I need it
rm(list = ls(all.names = TRUE))

```

## Load, join and filter data rush hour

```{r}

# import data
rural_interstate <- read.csv(here("input_data", "rural-state-interstate-data.csv"))
urban_interstate <- read.csv(here("input_data", "urban-state-interstate-data.csv"))
rural_other <- read.csv(here("input_data", "rural-state-other-data.csv"))
urban_other<- read.csv(here("input_data", "urban-state-other-data.csv"))

# clean name
rural_interstate <- clean_names(rural_interstate)
urban_interstate <- clean_names(urban_interstate)
rural_other <- clean_names(rural_other)
urban_other <- clean_names(urban_other)

# make the data numbers
rural_interstate <- rural_interstate %>%
  mutate(time = as.numeric(time),
         year = as.numeric(year),
         rural_avg = as.numeric(rural_avg),
         rural_per_hour = as.numeric(rural_per_hour))

urban_interstate <- urban_interstate %>%
  mutate(time = as.numeric(time),
         year = as.numeric(year),
         urban_avg = as.numeric(urban_avg),
         urban_per_hour = as.numeric(urban_per_hour))

rural_other <- rural_other %>%
  mutate(time = as.numeric(time),
         year = as.numeric(year),
         rural_avg = as.numeric(rural_avg),
         rural_per_hour = as.numeric(rural_per_hour))

urban_other <- urban_other %>%
  mutate(time = as.numeric(time),
         year = as.numeric(year),
         urban_avg = as.numeric(urban_avg),
         urban_per_hour = as.numeric(urban_per_hour))


#join rural and urban
traffic_interstate <- rural_interstate %>%
  inner_join(urban_interstate, by = c("time", "year"))
traffic_other <- rural_other %>%
  inner_join(urban_other, by = c("time", "year"))

# add data for rush hour
traffic_interstate <- traffic_interstate %>%
  mutate(rush_hour = case_when(time == 6 ~ 'am_rush',
                              time == 7 ~ 'am_rush',
                              time == 8 ~ 'am_rush',
                              time == 15 ~ 'pm_rush',
                              time == 16 ~ 'pm_rush',
                              time == 17 ~ 'pm_rush',
                              time == 18 ~ 'pm_rush', 
                             TRUE ~ 'na'))
traffic_other <- traffic_other %>%
  mutate(rush_hour = case_when(time == 6 ~ 'am_rush',
                              time == 7 ~ 'am_rush',
                              time == 8 ~ 'am_rush',
                              time == 15 ~ 'pm_rush',
                              time == 16 ~ 'pm_rush',
                              time == 17 ~ 'pm_rush',
                              time == 18 ~ 'pm_rush', 
                             TRUE ~ 'na'))

rm(rural_interstate)
rm(urban_interstate)
rm(rural_other)
rm(urban_other)

```

```{r}

glimpse(traffic_interstate)

```

## Analysis

```{r}
# The rural share of rush hour interstate traffic in the state of Maryland dropped drastically after reaching a high of 7.5% in 2009, rebounding to 7.6% in 2016.

rush_hour_interstate <- traffic_interstate %>%
  filter(str_detect(rush_hour, "rush")) %>%
  group_by(year) %>%
  summarise(rural_total = sum(rural_per_hour),
  urban_total = sum(urban_per_hour)) %>%
  mutate(rural_percent_of_total = (rural_total/(rural_total+urban_total)*100)) %>%
  mutate(urban_percent_of_total = (urban_total/(rural_total+urban_total)*100)) %>%
  select(year, rural_total, rural_percent_of_total, urban_total, urban_percent_of_total) %>%
  arrange(desc(year))

```


```{r}

ggplot(rush_hour_interstate) +
  geom_bar(stat="identity", aes(year, c(rural_total)), fill="gold") +
  labs(x="Year", y="Total drivers", title="Rural Weekday Rush Hour Interstate Traffic", subtitle = "The number of cars in rural areas during rush hour in Maryland has been increasing since 2013.", caption = "Source: Maryland State Highway Administration") +
  scale_x_continuous(breaks = c(2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016)) +
  scale_y_continuous(labels = comma) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```

```{r}
ggplot(rush_hour_interstate) +
  geom_bar(stat="identity", aes(year, c(urban_total)), fill="red") +
  labs(x="Year", y="Total drivers", title="Urban Weekday Rush Hour Interstate Traffic", subtitle = "The number of cars in urban areas during rush hour in Maryland has sharply dropped since 2013.", caption = "Source: Maryland State Highway Administration") +
  scale_x_continuous(breaks = c(2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016)) +
  scale_y_continuous(labels = comma) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
# The rural share of all interstate traffic in the state of Maryland has increased substantially since 2007, more than doubling.
total_interstate <- traffic_interstate %>%
  group_by(year) %>%
  summarise(rural_total = sum(rural_per_hour),
  urban_total = sum(urban_per_hour)) %>%
  mutate(rural_percent_of_total = (rural_total/(rural_total+urban_total)*100)) %>%
  mutate(urban_percent_of_total = (urban_total/(rural_total+urban_total)*100)) %>%
  select(year, rural_total, rural_percent_of_total, urban_total, urban_percent_of_total) %>%
  arrange(desc(year))

```

```{r}

ggplot(total_interstate) +
  geom_bar(stat="identity", aes(year, c(rural_total)), fill="gold") +
  labs(x="Year", y="Total drivers", title="Total Rural Weekday Interstate Traffic", subtitle = "The number of cars in rural areas in Maryland has been increasing since 2013.", caption = "Source: Maryland State Highway Administration") +
  scale_x_continuous(breaks = c(2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016)) +
  scale_y_continuous(labels = comma) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```

```{r}
ggplot(total_interstate) +
  geom_bar(stat="identity", aes(year, c(urban_total)), fill="red") +
  labs(x="Year", y="Total drivers", title="Total Urban Weekday Interstate Traffic", subtitle = "Urban weekday traffic has been dropping since 2012. It is almost half of 2008 data since 2016.", caption = "Source: Maryland State Highway Administration") +
  scale_x_continuous(breaks = c(2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016)) +
  scale_y_continuous(labels = comma) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
# The rural share of all rush hour non-interestate traffic in the state of Maryland has drastically increased since 2007 because urban traffic is dropping.  

rush_hour_other <- traffic_other %>%
  filter(rush_hour == "am_rush") %>%
  group_by(year) %>%
  summarise(rural_total = sum(rural_per_hour),
            urban_total = sum(urban_per_hour)) %>%
  mutate(rural_percent_of_total = (rural_total/(rural_total+urban_total)*100)) %>%
    mutate(urban_percent_of_total = (urban_total/(rural_total+urban_total)*100)) %>%
  select(year, rural_total, rural_percent_of_total, urban_total, urban_percent_of_total) %>%
  arrange(desc(year))

```

```{r}

ggplot(rush_hour_other) +
  geom_bar(stat="identity", aes(year, c(rural_total)), fill="gold") +
  labs(x="Year", y="Total drivers", title="Rural Weekday Non-Interstate Rush House Traffic", subtitle = "", caption = "Source: Maryland State Highway Administration") +
  scale_x_continuous(breaks = c(2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016)) +
  scale_y_continuous(labels = comma) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```

```{r}
ggplot(rush_hour_other) +
  geom_bar(stat="identity", aes(year, c(urban_total)), fill="red") +
  labs(x="Year", y="Total drivers", title="Urban Weekday Non-Interstate Rush Hour Traffic", subtitle = "", caption = "Source: Maryland State Highway Administration") +
  scale_x_continuous(breaks = c(2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016)) +
  scale_y_continuous(labels = comma) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}

# note
total_other <- traffic_other %>%
  group_by(year) %>%
  summarise(rural_total = sum(rural_per_hour),
  urban_total = sum(urban_per_hour)) %>%
  mutate(rural_percent_of_total = (rural_total/(rural_total+urban_total)*100)) %>%
  mutate(urban_percent_of_total = (urban_total/(rural_total+urban_total)*100)) %>%
  select(year, rural_total, rural_percent_of_total, urban_total, urban_percent_of_total) %>%
  arrange(desc(year))

```

```{r}

ggplot(total_other) +
  geom_bar(stat="identity", aes(year, c(rural_total)), fill="gold") +
  labs(x="Year", y="Total drivers", title="Total Rural Weekday Non-Interstate Traffic", subtitle = "", caption = "Source: Maryland State Highway Administration") +
  scale_x_continuous(breaks = c(2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016)) +
  scale_y_continuous(labels = comma) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```

```{r}
ggplot(total_other) +
  geom_bar(stat="identity", aes(year, c(urban_total)), fill="red") +
  labs(x="Year", y="Total drivers", title="Total Urban Weekday Non-Interstate Traffic", subtitle = "Urban weekday traffic has been dropping since 2012. It is almost half of 2008 data since 2016.", caption = "Source: Maryland State Highway Administration") +
  scale_x_continuous(breaks = c(2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016)) +
  scale_y_continuous(labels = comma) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```


```{r}

average_daily_traffic <- read_csv(here("input_data", "Maryland_Annual_Average_Daily_Traffic__Annual_Average_Daily_Traffic_SHA_Statewide_AADT_Lines.csv"))

```

```{r}
# making all names lowercase
average_daily_traffic <- clean_names(average_daily_traffic)

glimpse(average_daily_traffic)

```

```{r}
# changing N/A to 0
average_daily_traffic[is.na(average_daily_traffic)] <- 0
```




```{r}
# count total average weekday drivers by county
county_total_average <- average_daily_traffic %>%
  group_by(county_desc) %>%
  summarise(total_2017 = sum(aawdt_2017),
            total_2016 = sum(aawdt_2016),
            total_2015 = sum(aawdt_2015),
            total_2014 = sum(aawdt_2014),
            total_2013 = sum(aawdt_2013),
            total_2012 = sum(aawdt_2012),
            total_2011 = sum(aawdt_2011),
            total_2010 = sum(aawdt_2010),
            total_2009 = sum(aawdt_2009))
```



```{r}
# add state total average weekday drivers
state_total_average <- county_total_average %>%

  rbind(c("state_total", 
          (sum(.$total_2017)), 
          (sum(.$total_2016)), 
          (sum(.$total_2015)),
          (sum(.$total_2014)),
          (sum(.$total_2013)),
          (sum(.$total_2012)),
          (sum(.$total_2011)),
          (sum(.$total_2010)),
          (sum(.$total_2009))))

```


```{r}

state_only_total_average <- average_daily_traffic %>%
  mutate(state = "maryland") %>%
  group_by(state) %>%
  summarise(total_2017 = sum(aawdt_2017),
            total_2016 = sum(aawdt_2016),
            total_2015 = sum(aawdt_2015),
            total_2014 = sum(aawdt_2014),
            total_2013 = sum(aawdt_2013),
            total_2012 = sum(aawdt_2012),
            total_2011 = sum(aawdt_2011),
            total_2010 = sum(aawdt_2010),
            total_2009 = sum(aawdt_2009)) %>%
  rbind(c("2009", .$total_2009)) %>%
  rbind(c("2010", .$total_2010)) %>%
  rbind(c("2011", .$total_2011)) %>%
  rbind(c("2012", .$total_2012)) %>%
  rbind(c("2013", .$total_2013)) %>%
  rbind(c("2014", .$total_2014)) %>%
  rbind(c("2015", .$total_2015)) %>%
  rbind(c("2016", .$total_2016)) %>%
  rbind(c("2017", .$total_2017)) %>%
  select(c(-total_2016,
          -total_2015,
          -total_2014,
          -total_2013,
          -total_2012,
          -total_2011,
          -total_2010,
          -total_2009)) %>%
  slice(2:10) %>%
  rename(year = state) %>%
  rename(total_avg_drv = total_2017)

```


```{r}

ggplot(state_only_total_average) +
  geom_bar(aes(year, c(total_avg_drv)), stat="identity", fill="red") +
  labs(x="Year", y="Total drivers", title="x", subtitle = "", caption = "Source: Maryland State Highway Administration")
```



